'use strict';

/**
 * scriptGenerator.js
 * Generates self-contained bash playback scripts for ASCII animations.
 * Scripts are compatible with Linux, macOS, and WSL (Windows Subsystem for Linux).
 */

/**
 * Escape a string for safe embedding in a bash heredoc.
 * We use a unique delimiter to avoid collisions.
 * @param {string} text
 * @returns {string}
 */
function bashEscapeFrame(text) {
  // Replace backslashes to prevent interpretation, then dollar signs
  return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

/**
 * Generate a self-contained bash script that embeds all ASCII frames
 * and loops them at the specified FPS.
 *
 * @param {Array<{ ascii: string, delay: number }>} frames - ASCII frame data
 * @param {object} options
 * @param {string} options.gifName - Original GIF filename
 * @param {number} options.defaultFps - Default playback FPS
 * @param {string} options.densityPreset - Density preset name
 * @param {number} options.asciiWidth - ASCII width in columns
 * @returns {string} Bash script content
 */
function generatePlaybackScript(frames, options = {}) {
  const {
    gifName = 'animation',
    defaultFps = 10,
    densityPreset = 'standard',
    asciiWidth = 80,
  } = options;

  const frameCount = frames.length;
  const generatedAt = new Date().toISOString();

  // Build frame variable declarations using heredocs
  const frameDeclarations = frames.map((frame, i) => {
    const escaped = bashEscapeFrame(frame.ascii);
    return `FRAME_${i}=$(cat <<'ASCIIFRAME_${i}'\n${frame.ascii}\nASCIIFRAME_${i}\n)`;
  });

  // Build frame array reference
  const frameArrayEntries = frames.map((_, i) => `  "$FRAME_${i}"`).join('\n');

  // Build per-frame delay array (in fractional seconds)
  const delayArray = frames.map((f) => {
    const secs = ((f.delay || 100) / 1000).toFixed(4);
    return `  "${secs}"`;
  });

  return `#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
#   ASCII Terminal GIF Player
#   Generated by ASCII Terminal GIF Converter
#
#   Source GIF  : ${gifName}
#   Frames      : ${frameCount}
#   ASCII Width : ${asciiWidth} cols
#   Density     : ${densityPreset}
#   Generated   : ${generatedAt}
#
#   Usage: ./play_ascii.sh [fps] [loops]
#          fps   - Override playback speed (default: ${defaultFps})
#          loops - Number of loops, 0 = infinite (default: 0)
#
#   Compatible with: bash 3.2+, Linux, macOS, WSL
# ═══════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────
OVERRIDE_FPS="${1:-0}"
MAX_LOOPS="${2:-0}"
DEFAULT_FPS=${defaultFps}

# ── Terminal utilities ─────────────────────────────────────────────
hide_cursor()   { printf '\\033[?25l'; }
show_cursor()   { printf '\\033[?25h'; }
clear_screen()  { printf '\\033[H\\033[2J'; }
move_home()     { printf '\\033[H'; }
bold_on()       { printf '\\033[1m'; }
reset_attrs()   { printf '\\033[0m'; }
set_green()     { printf '\\033[32m'; }

# ── Cleanup on exit ────────────────────────────────────────────────
cleanup() {
  show_cursor
  reset_attrs
  clear_screen
  echo ""
  echo "  ASCII Terminal GIF Player — stopped."
  exit 0
}
trap cleanup INT TERM EXIT

# ── Dependency check ───────────────────────────────────────────────
check_deps() {
  local missing=()
  command -v bc >/dev/null 2>&1 || missing+=("bc")
  command -v sleep >/dev/null 2>&1 || missing+=("sleep")
  if [[ \${#missing[@]} -gt 0 ]]; then
    echo "ERROR: Missing required commands: \${missing[*]}"
    echo "Install them with your package manager (e.g. apt, brew) and retry."
    exit 1
  fi
}
check_deps

# ── Frame data ─────────────────────────────────────────────────────
# Each frame is stored as a bash variable using heredoc syntax.
# Frame delays are in seconds (float).

${frameDeclarations.join('\n\n')}

# Frame array
FRAMES=(
${frameArrayEntries}
)

# Per-frame delays (seconds)
DELAYS=(
${delayArray.join('\n')}
)

TOTAL_FRAMES=${frameCount}

# ── Playback ───────────────────────────────────────────────────────
hide_cursor
clear_screen

loop_count=0
frame_idx=0

while true; do
  # Check loop limit
  if [[ $MAX_LOOPS -gt 0 && $loop_count -ge $MAX_LOOPS ]]; then
    break
  fi

  frame_idx=0
  while [[ $frame_idx -lt $TOTAL_FRAMES ]]; do
    move_home
    set_green
    printf '%s' "\${FRAMES[$frame_idx]}"
    reset_attrs

    # Determine delay
    if [[ "$OVERRIDE_FPS" != "0" ]] && [[ "$OVERRIDE_FPS" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
      DELAY=$(echo "scale=6; 1 / $OVERRIDE_FPS" | bc 2>/dev/null || echo "0.1")
    else
      DELAY="\${DELAYS[$frame_idx]}"
    fi

    sleep "$DELAY"
    ((frame_idx++)) || true
  done

  ((loop_count++)) || true
done

cleanup
`;
}

/**
 * Generate a simpler, directory-based script that reads frames from ./frames/ folder.
 * More human-readable but requires the frames directory to exist alongside it.
 *
 * @param {number} frameCount
 * @param {object} options
 * @returns {string}
 */
function generateDirectoryScript(frameCount, options = {}) {
  const { defaultFps = 10, gifName = 'animation' } = options;

  return `#!/usr/bin/env bash
# ASCII Terminal GIF Player (Directory Mode)
# Reads frame files from ./frames/frame_*.txt
#
# Usage: ./play_ascii.sh [fps]

FPS="\${1:-${defaultFps}}"
FRAMES_DIR="./frames"

hide_cursor() { printf '\\033[?25l'; }
show_cursor() { printf '\\033[?25h'; }
trap 'show_cursor; printf "\\033[0m\\n"; exit 0' INT TERM

hide_cursor
printf '\\033[H\\033[2J'

while true; do
  for frame_file in $(ls "\$FRAMES_DIR"/frame_*.txt 2>/dev/null | sort -V); do
    printf '\\033[H'
    printf '\\033[32m'
    cat "\$frame_file"
    printf '\\033[0m'
    sleep "$(echo "scale=4; 1 / \$FPS" | bc)"
  done
done
`;
}

module.exports = { generatePlaybackScript, generateDirectoryScript };
